version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  # Remove this block; you'll set up a push-driven submodule update workflow
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
  # - package-ecosystem: <your package manager here>
  #   directory: /
  #   schedule:
  #     interval: weekly
